version: '3.8'

services:
  api:
    image: thobui2105/demo-api:v1
    container_name: api
    restart: unless-stopped
    networks:
      - thobt-net

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
    depends_on:
      - api
    networks:
      - thobt-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email thob2105@gmail.com --agree-tos --no-eff-email --force-renewal -d api.thobt.online

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/api/html
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/docker/dhparam/
      o: bind

networks:
  thobt-net:
    driver: bridge